scala_library(name = 'rout',
  dependencies = [
     'projects3/rOut/core/src/io/rout:core',
     'projects3/rOut/routing/src/io/rout/routing',

  ],
    sources = globs('*.scala','internal/*.scala'),
) 
