scala_library(name = 'path',
  dependencies = [
        '3rdparty/jvm/com/twitter:finagle-http',
        '3rdparty/jvm/com/twitter:util-eval',
        '3rdparty/jvm/com/chuusai/shapeless:shapeless',
  ],
  sources = globs('*.scala'),
)
