scala_library(name = 'decoding',
  dependencies = [
     'projects3/rOut/core/src/io:rout',
     '3rdparty/jvm/com/chuusai/shapeless:shapeless',
     '3rdparty/jvm/com/twitter:finagle-http',
     '3rdparty/jvm/org/typelevel:export-hook',
     '3rdparty/jvm/com/twitter:util-eval',
     '3rdparty/jvm/org/typelevel:cats-core',
  ],
    sources = globs('*.scala'),
) 
