scala_library(name = 'enums',
  dependencies = [
     '3rdparty/jvm/com/twitter:util-eval',
     '3rdparty/jvm/com/chuusai/shapeless:shapeless',
     '3rdparty/jvm/io/circe:core',
  ],
    sources = globs('*.scala'),
) 
