scala_library(name = 'routing',
  dependencies = [
        '3rdparty/jvm/com/twitter:finagle-http',
        'projects/finagle/finagle-http/src/scala/com/teodimoff/finagle/http/finch/src/scala/finch/finagle',
        'projects/finagle/finagle-http/src/scala/com/teodimoff/finagle/http/file',
        'projects3/rOut/path/src/io/rout/path',
        'projects3/rOut/file/src/io/rout/file',
        'projects3/rOut/core/src/io/rout:core',
  ],
  sources = globs('*.scala'),
) 
