scala_library(name = 'circe',
  dependencies = [
     '3rdparty/jvm/io/circe:core',
     '3rdparty/jvm/io/circe:jawn',
     '3rdparty/jvm/io/circe:generic',
     '3rdparty/jvm/io/circe:jackson',
     'projects3/rOut/core/src/io:rout',
  ],
    sources = globs('*.scala'),
)
