scala_library(name = 'incomplete',
  dependencies = [
     'projects3/rOut/generic/src/io/rout/decode:decoding',
     '3rdparty/jvm/com/twitter:finagle-http',
     '3rdparty/jvm/com/twitter:twitter-server',
  ],
    sources = globs('*.scala'),
) 
