scala_library(name = 'core',
  dependencies = [
     '3rdparty/jvm/org/typelevel:cats-core',
     '3rdparty/jvm/com/chuusai/shapeless:shapeless',
     '3rdparty/jvm/com/twitter:finagle-http',
     '3rdparty/jvm/org/typelevel:export-hook',
     'projects/finagle/finagle-http/src/scala/com/teodimoff/finagle/http/html',
     '3rdparty/jvm/com/twitter:util-eval',
  ],
    sources = globs('*.scala','internal/*.scala'),
) 
