scala_library(name = 'html',
  dependencies = [
        '3rdparty/jvm/com/twitter:finagle-http',
#        '3rdparty/jvm/com/twitter:util-core',
        '3rdparty/jvm/com/github/lihaoyi/scalatags',
  ],
  sources = globs('*.scala'),
)