scala_library(name = 'xml',
  dependencies = [
     'projects3/rOut/core/src/io:rout',
     '3rdparty/jvm/org/typelevel:cats-core',
     '3rdparty/jvm/com/twitter:util-core',
     '3rdparty/jvm/org/scalaz:scalaz-core',
     '3rdparty/jvm/com/chuusai/shapeless:shapeless',
  ],
    sources = globs('*.scala'),
)

scala_library(name = 'xml-cats',
  dependencies = [
     'projects3/rOut/core/src/io:rout',
     '3rdparty/jvm/org/typelevel:cats-core',
     '3rdparty/jvm/com/twitter:util-core',
     '3rdparty/jvm/com/chuusai/shapeless:shapeless',
  ],
    sources = globs('*.scala'),
)